[package]
name = "zwift_presence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
discord-rich-presence = "0.2.3"
env_logger = "0.10.0"
fitparser = "0.5.1"
log = "0.4.17"
